name: Linux

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'JuceLibraryCode/**'
    - 'PluginGenerator/**'
    - 'Plugins/**'
    - 'Resources/**'
    - 'Source/**'
    - 'CMakeLists.txt'
    - 'HelperFunctions.cmake'

jobs:
  build-ubuntu:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        CC: gcc-10
        CXX: g++-10
      run: |
        sudo apt update
        cd Resources/Scripts
        sudo ./install_linux_dependencies.sh
        cd ../../Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        make -j4
#    - name: test
#      run: cd build && ctest
    - name: deploy_dev
      if: github.ref == 'refs/heads/development-juce8'
      env:
        artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
      run: |
        cd Build
        cp -r Release open-ephys
        cp ../LICENSE open-ephys
        zipfile=open-ephys-v1.0.0-dev-linux.zip
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$artifactoryApiKey"
        curl -H $user_info -T $zipfile "https://openephysgui.jfrog.io/artifactory/1.0.0-dev/linux/$zipfile"
      shell: bash
    - name: deploy_preview
      if: github.ref_type == 'tag'
      env:
        artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        cd Build
        cp -r Release open-ephys
        cp ../LICENSE open-ephys
        zipfile=open-ephys-${gui_ver}-linux.zip
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$artifactoryApiKey"
        curl -H $user_info -T $zipfile "https://openephysgui.jfrog.io/artifactory/1.0.0-pre/linux/$zipfile"
      shell: bash
